/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * BatVault Gateway
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query'
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query'
import axios from 'axios'
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios'
export type V3QueryV3QueryPostParams = {
stream?: boolean;
include_event?: boolean;
fresh?: boolean;
template?: string | null;
org?: string | null;
};

export type OpsMinioLsV3OpsMinioLsRequestIdGetParams = {
prefix?: string | null;
limit?: number;
};

export type OpsMinioHeadV3OpsMinioHeadRequestIdGetParams = {
name?: string;
};

export type GetPublicConfigConfigGet200 = { [key: string]: unknown };

/**
 * @nullable
 */
export type WhyDecisionResponseCompletenessFlags = CompletenessFlags | null;

export interface WhyDecisionAnswerOutput {
  blocks: AnswerBlocks;
  [key: string]: unknown;
 }

export interface WhyDecisionResponse {
  anchor: WhyDecisionAnchor;
  answer: WhyDecisionAnswerOutput;
  /** @nullable */
  completeness_flags?: WhyDecisionResponseCompletenessFlags;
  graph: GraphEdgesModel;
  meta: MemoryMetaModel;
  [key: string]: unknown;
 }

export interface WhyDecisionAnswerInput {
  blocks: AnswerBlocks;
  [key: string]: unknown;
 }

export interface WhyDecisionAnchor { [key: string]: unknown }

export type ValidationErrorLocItem = string | number;

export interface ValidationError {
  loc: ValidationErrorLocItem[];
  msg: string;
  type: string;
}

/**
 * @nullable
 */
export type QueryRequestPolicy = { [key: string]: unknown } | null;

/**
 * @nullable
 */
export type QueryRequestGraph = { [key: string]: unknown } | null;

export interface QueryRequest {
  /** @nullable */
  anchor?: string | null;
  /** @nullable */
  graph?: QueryRequestGraph;
  /** @nullable */
  policy?: QueryRequestPolicy;
  /** @minLength 1 */
  question: string;
  [key: string]: unknown;
 }

export interface MemoryMetaModel {
  /** @nullable */
  allowed_ids_fp?: string | null;
  /** @nullable */
  policy_fp?: string | null;
  /** @nullable */
  snapshot_etag?: string | null;
  [key: string]: unknown;
 }

export interface HTTPValidationError {
  detail?: ValidationError[];
}

export type GraphEdgesModelEdgesItem = { [key: string]: unknown };

export interface GraphEdgesModel {
  edges?: GraphEdgesModelEdgesItem[];
  [key: string]: unknown;
 }

export interface CompletenessFlags { [key: string]: unknown }

export interface AnswerOwner {
  name: string;
  /** @nullable */
  role?: string | null;
}

/**
 * @nullable
 */
export type AnswerBlocksOwner = AnswerOwner | null;

export interface AnswerBlocks {
  /** @nullable */
  decision_id?: string | null;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  key_events?: string[] | null;
  lead: string;
  /** @nullable */
  next?: string | null;
  /** @nullable */
  owner?: AnswerBlocksOwner;
}





/**
 * @summary Get Public Config
 */
export const getPublicConfigConfigGet = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<GetPublicConfigConfigGet200>> => {
    
    return axios.get(
      `/config`,options
    );
  }


export const getGetPublicConfigConfigGetQueryKey = () => {
    return [`/config`] as const;
    }

    
export const getGetPublicConfigConfigGetQueryOptions = <TData = Awaited<ReturnType<typeof getPublicConfigConfigGet>>, TError = AxiosError<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPublicConfigConfigGet>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPublicConfigConfigGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPublicConfigConfigGet>>> = ({ signal }) => getPublicConfigConfigGet({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPublicConfigConfigGet>>, TError, TData> & { queryKey: QueryKey }
}

export type GetPublicConfigConfigGetQueryResult = NonNullable<Awaited<ReturnType<typeof getPublicConfigConfigGet>>>
export type GetPublicConfigConfigGetQueryError = AxiosError<unknown>

/**
 * @summary Get Public Config
 */
export const useGetPublicConfigConfigGet = <TData = Awaited<ReturnType<typeof getPublicConfigConfigGet>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPublicConfigConfigGet>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getGetPublicConfigConfigGetQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary  Healthz
 */
export const healthzHealthzGet = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {
    
    return axios.get(
      `/healthz`,options
    );
  }


export const getHealthzHealthzGetQueryKey = () => {
    return [`/healthz`] as const;
    }

    
export const getHealthzHealthzGetQueryOptions = <TData = Awaited<ReturnType<typeof healthzHealthzGet>>, TError = AxiosError<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthzHealthzGet>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getHealthzHealthzGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof healthzHealthzGet>>> = ({ signal }) => healthzHealthzGet({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof healthzHealthzGet>>, TError, TData> & { queryKey: QueryKey }
}

export type HealthzHealthzGetQueryResult = NonNullable<Awaited<ReturnType<typeof healthzHealthzGet>>>
export type HealthzHealthzGetQueryError = AxiosError<unknown>

/**
 * @summary  Healthz
 */
export const useHealthzHealthzGet = <TData = Awaited<ReturnType<typeof healthzHealthzGet>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthzHealthzGet>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getHealthzHealthzGetQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Thin pass-through so the browser can call Memory via the Gateway origin.
Uses the shared AsyncClient from core_http.client.
 * @summary Proxy Memory
 */
export const proxyMemoryMemoryPathDelete = (
    path: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {
    
    return axios.put(
      `/memory/${path}`,undefined,options
    );
  }



export const getProxyMemoryMemoryPathDeleteMutationOptions = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof proxyMemoryMemoryPathDelete>>, TError,{path: string}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof proxyMemoryMemoryPathDelete>>, TError,{path: string}, TContext> => {
const {mutation: mutationOptions, axios: axiosOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof proxyMemoryMemoryPathDelete>>, {path: string}> = (props) => {
          const {path} = props ?? {};

          return  proxyMemoryMemoryPathDelete(path,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ProxyMemoryMemoryPathDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof proxyMemoryMemoryPathDelete>>>
    
    export type ProxyMemoryMemoryPathDeleteMutationError = AxiosError<HTTPValidationError>

    /**
 * @summary Proxy Memory
 */
export const useProxyMemoryMemoryPathDelete = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof proxyMemoryMemoryPathDelete>>, TError,{path: string}, TContext>, axios?: AxiosRequestConfig}
): UseMutationResult<
        Awaited<ReturnType<typeof proxyMemoryMemoryPathDelete>>,
        TError,
        {path: string},
        TContext
      > => {

      const mutationOptions = getProxyMemoryMemoryPathDeleteMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
/**
 * @summary Ensure Bucket
 */
export const ensureBucketOpsMinioEnsureBucketPost = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {
    
    return axios.post(
      `/ops/minio/ensure-bucket`,undefined,options
    );
  }



export const getEnsureBucketOpsMinioEnsureBucketPostMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof ensureBucketOpsMinioEnsureBucketPost>>, TError,void, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof ensureBucketOpsMinioEnsureBucketPost>>, TError,void, TContext> => {
const {mutation: mutationOptions, axios: axiosOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof ensureBucketOpsMinioEnsureBucketPost>>, void> = () => {
          

          return  ensureBucketOpsMinioEnsureBucketPost(axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type EnsureBucketOpsMinioEnsureBucketPostMutationResult = NonNullable<Awaited<ReturnType<typeof ensureBucketOpsMinioEnsureBucketPost>>>
    
    export type EnsureBucketOpsMinioEnsureBucketPostMutationError = AxiosError<unknown>

    /**
 * @summary Ensure Bucket
 */
export const useEnsureBucketOpsMinioEnsureBucketPost = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof ensureBucketOpsMinioEnsureBucketPost>>, TError,void, TContext>, axios?: AxiosRequestConfig}
): UseMutationResult<
        Awaited<ReturnType<typeof ensureBucketOpsMinioEnsureBucketPost>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getEnsureBucketOpsMinioEnsureBucketPostMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
/**
 * @summary  Readyz
 */
export const readyzReadyzGet = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {
    
    return axios.get(
      `/readyz`,options
    );
  }


export const getReadyzReadyzGetQueryKey = () => {
    return [`/readyz`] as const;
    }

    
export const getReadyzReadyzGetQueryOptions = <TData = Awaited<ReturnType<typeof readyzReadyzGet>>, TError = AxiosError<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof readyzReadyzGet>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getReadyzReadyzGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof readyzReadyzGet>>> = ({ signal }) => readyzReadyzGet({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof readyzReadyzGet>>, TError, TData> & { queryKey: QueryKey }
}

export type ReadyzReadyzGetQueryResult = NonNullable<Awaited<ReturnType<typeof readyzReadyzGet>>>
export type ReadyzReadyzGetQueryError = AxiosError<unknown>

/**
 * @summary  Readyz
 */
export const useReadyzReadyzGet = <TData = Awaited<ReturnType<typeof readyzReadyzGet>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof readyzReadyzGet>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getReadyzReadyzGetQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Diagnostic: expose the *effective* MinIO settings this process is using.
Secrets are not returned.
 * @summary Ops Minio Config
 */
export const opsMinioConfigV3OpsMinioConfigGet = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {
    
    return axios.get(
      `/v3/ops/minio/config`,options
    );
  }


export const getOpsMinioConfigV3OpsMinioConfigGetQueryKey = () => {
    return [`/v3/ops/minio/config`] as const;
    }

    
export const getOpsMinioConfigV3OpsMinioConfigGetQueryOptions = <TData = Awaited<ReturnType<typeof opsMinioConfigV3OpsMinioConfigGet>>, TError = AxiosError<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof opsMinioConfigV3OpsMinioConfigGet>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getOpsMinioConfigV3OpsMinioConfigGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof opsMinioConfigV3OpsMinioConfigGet>>> = ({ signal }) => opsMinioConfigV3OpsMinioConfigGet({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof opsMinioConfigV3OpsMinioConfigGet>>, TError, TData> & { queryKey: QueryKey }
}

export type OpsMinioConfigV3OpsMinioConfigGetQueryResult = NonNullable<Awaited<ReturnType<typeof opsMinioConfigV3OpsMinioConfigGet>>>
export type OpsMinioConfigV3OpsMinioConfigGetQueryError = AxiosError<unknown>

/**
 * @summary Ops Minio Config
 */
export const useOpsMinioConfigV3OpsMinioConfigGet = <TData = Awaited<ReturnType<typeof opsMinioConfigV3OpsMinioConfigGet>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof opsMinioConfigV3OpsMinioConfigGet>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getOpsMinioConfigV3OpsMinioConfigGetQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Diagnostic: stat an object for a given request_id.
Now supports *both*:
  - archive names:  bundle_view / bundle_full  →  <rid>/<name>.tar.gz
  - artifact names: receipt.json / response.json / trace.json / bundle.manifest.json → <rid>/<name>
 * @summary Ops Minio Head
 */
export const opsMinioHeadV3OpsMinioHeadRequestIdGet = (
    requestId: string,
    params?: OpsMinioHeadV3OpsMinioHeadRequestIdGetParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {
    
    return axios.get(
      `/v3/ops/minio/head/${requestId}`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }


export const getOpsMinioHeadV3OpsMinioHeadRequestIdGetQueryKey = (requestId: string,
    params?: OpsMinioHeadV3OpsMinioHeadRequestIdGetParams,) => {
    return [`/v3/ops/minio/head/${requestId}`, ...(params ? [params]: [])] as const;
    }

    
export const getOpsMinioHeadV3OpsMinioHeadRequestIdGetQueryOptions = <TData = Awaited<ReturnType<typeof opsMinioHeadV3OpsMinioHeadRequestIdGet>>, TError = AxiosError<HTTPValidationError>>(requestId: string,
    params?: OpsMinioHeadV3OpsMinioHeadRequestIdGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof opsMinioHeadV3OpsMinioHeadRequestIdGet>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getOpsMinioHeadV3OpsMinioHeadRequestIdGetQueryKey(requestId,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof opsMinioHeadV3OpsMinioHeadRequestIdGet>>> = ({ signal }) => opsMinioHeadV3OpsMinioHeadRequestIdGet(requestId,params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(requestId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof opsMinioHeadV3OpsMinioHeadRequestIdGet>>, TError, TData> & { queryKey: QueryKey }
}

export type OpsMinioHeadV3OpsMinioHeadRequestIdGetQueryResult = NonNullable<Awaited<ReturnType<typeof opsMinioHeadV3OpsMinioHeadRequestIdGet>>>
export type OpsMinioHeadV3OpsMinioHeadRequestIdGetQueryError = AxiosError<HTTPValidationError>

/**
 * @summary Ops Minio Head
 */
export const useOpsMinioHeadV3OpsMinioHeadRequestIdGet = <TData = Awaited<ReturnType<typeof opsMinioHeadV3OpsMinioHeadRequestIdGet>>, TError = AxiosError<HTTPValidationError>>(
 requestId: string,
    params?: OpsMinioHeadV3OpsMinioHeadRequestIdGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof opsMinioHeadV3OpsMinioHeadRequestIdGet>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getOpsMinioHeadV3OpsMinioHeadRequestIdGetQueryOptions(requestId,params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Diagnostic: list objects under a prefix (defaults to f"{request_id}/").
Same-origin; avoids CORS. Helps verify bucket/endpoint/prefix alignment.
 * @summary Ops Minio Ls
 */
export const opsMinioLsV3OpsMinioLsRequestIdGet = (
    requestId: string,
    params?: OpsMinioLsV3OpsMinioLsRequestIdGetParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {
    
    return axios.get(
      `/v3/ops/minio/ls/${requestId}`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }


export const getOpsMinioLsV3OpsMinioLsRequestIdGetQueryKey = (requestId: string,
    params?: OpsMinioLsV3OpsMinioLsRequestIdGetParams,) => {
    return [`/v3/ops/minio/ls/${requestId}`, ...(params ? [params]: [])] as const;
    }

    
export const getOpsMinioLsV3OpsMinioLsRequestIdGetQueryOptions = <TData = Awaited<ReturnType<typeof opsMinioLsV3OpsMinioLsRequestIdGet>>, TError = AxiosError<HTTPValidationError>>(requestId: string,
    params?: OpsMinioLsV3OpsMinioLsRequestIdGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof opsMinioLsV3OpsMinioLsRequestIdGet>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getOpsMinioLsV3OpsMinioLsRequestIdGetQueryKey(requestId,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof opsMinioLsV3OpsMinioLsRequestIdGet>>> = ({ signal }) => opsMinioLsV3OpsMinioLsRequestIdGet(requestId,params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(requestId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof opsMinioLsV3OpsMinioLsRequestIdGet>>, TError, TData> & { queryKey: QueryKey }
}

export type OpsMinioLsV3OpsMinioLsRequestIdGetQueryResult = NonNullable<Awaited<ReturnType<typeof opsMinioLsV3OpsMinioLsRequestIdGet>>>
export type OpsMinioLsV3OpsMinioLsRequestIdGetQueryError = AxiosError<HTTPValidationError>

/**
 * @summary Ops Minio Ls
 */
export const useOpsMinioLsV3OpsMinioLsRequestIdGet = <TData = Awaited<ReturnType<typeof opsMinioLsV3OpsMinioLsRequestIdGet>>, TError = AxiosError<HTTPValidationError>>(
 requestId: string,
    params?: OpsMinioLsV3OpsMinioLsRequestIdGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof opsMinioLsV3OpsMinioLsRequestIdGet>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getOpsMinioLsV3OpsMinioLsRequestIdGetQueryOptions(requestId,params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary V3 Query
 */
export const v3QueryV3QueryPost = (
    queryRequest: QueryRequest,
    params?: V3QueryV3QueryPostParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<WhyDecisionResponse>> => {
    
    return axios.post(
      `/v3/query`,
      queryRequest,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }



export const getV3QueryV3QueryPostMutationOptions = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof v3QueryV3QueryPost>>, TError,{data: QueryRequest;params?: V3QueryV3QueryPostParams}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof v3QueryV3QueryPost>>, TError,{data: QueryRequest;params?: V3QueryV3QueryPostParams}, TContext> => {
const {mutation: mutationOptions, axios: axiosOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof v3QueryV3QueryPost>>, {data: QueryRequest;params?: V3QueryV3QueryPostParams}> = (props) => {
          const {data,params} = props ?? {};

          return  v3QueryV3QueryPost(data,params,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type V3QueryV3QueryPostMutationResult = NonNullable<Awaited<ReturnType<typeof v3QueryV3QueryPost>>>
    export type V3QueryV3QueryPostMutationBody = QueryRequest
    export type V3QueryV3QueryPostMutationError = AxiosError<HTTPValidationError>

    /**
 * @summary V3 Query
 */
export const useV3QueryV3QueryPost = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof v3QueryV3QueryPost>>, TError,{data: QueryRequest;params?: V3QueryV3QueryPostParams}, TContext>, axios?: AxiosRequestConfig}
): UseMutationResult<
        Awaited<ReturnType<typeof v3QueryV3QueryPost>>,
        TError,
        {data: QueryRequest;params?: V3QueryV3QueryPostParams},
        TContext
      > => {

      const mutationOptions = getV3QueryV3QueryPostMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
